config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }

  resource :user_profile, only: [:show, :edit, :update]
  resource :quiz, only: [:new, :create, :destroy] do
    get  :question, on: :member
    post :answer,   on: :member
    get  :result,   on: :member
  end

  root to: 'home#welcome'
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_quiz_started, except: [:new, :create]
  before_action :require_quiz_not_started, only: [:new]

  def new
  end

  def create
    session[:current_quiz] = Quiz.new(user_id: current_user.id, conditions: condition_params)
    redirect_to question_quiz_path
  end

  def destroy
    session.delete(:current_quiz)
    redirect_to new_quiz_path
  end

  def question
    @current_quiz = Quiz.new(session[:current_quiz].with_indifferent_access)
    @question     = @current_quiz.next_question
  end

  def answer
    @current_quiz = Quiz.new(session[:current_quiz].with_indifferent_access)
    @current_quiz.answer!(params[:answer_name])
    session[:current_quiz] = @current_quiz
    redirect_to result_quiz_path
  end

  def result
    @current_quiz = Quiz.new(session[:current_quiz].with_indifferent_access)
    @question     = @current_quiz.last_question
    @result       = @current_quiz.last_result
  end

  private

  def condition_params
    params.permit(:group_id, :project_id, :joined_year)
  end

  def require_quiz_started
    redirect_to new_quiz_path if session[:current_quiz].blank?
  end

  def require_quiz_not_started
    redirect_to question_quiz_path if session[:current_quiz].present?
  end
end

app/views/quizzes/_start_form.html.haml
= form_tag quiz_path, method: :post do
  .form-group
  = submit_tag I18n.t('quiz.new.start_quiz'), class: 'btn btn-primary margin-bottom', autofocus: true
  .h4= I18n.t('quiz.new.filter')
  .form-group
    = label :joined_year, I18n.t('quiz.new.joined_year')
    = select_tag :joined_year, options_for_select(joined_years_selection, selected: params['joined_year']), include_blank: true, class: 'form-control'
  .form-group
    = label :project_id, I18n.t('quiz.new.project')
    = select_tag :project_id, options_from_collection_for_select(projects, :id, :name, selected: params['project_id']), include_blank: true, class: 'form-control'
  .form-group
    = label :group_id, I18n.t('quiz.new.group')
    = select_tag :group_id, options_from_collection_for_select(groups, :id, :name, selected: params['group_id']), include_blank: true, class: 'form-control'

app/views/quizzes/new.html.haml
= render 'start_form'

app/views/quizzes/question.html.haml
- if @question.blank?
  = I18n.t('quiz.question.no_questions')
  = render 'start_form'
- else
  = image_tag @question.profile_image_url(:normal), id: "question_image", 'data-user-id' => "#{@question.user.id}"
  #main-message
    = I18n.t('quiz.question.who')
  = form_tag answer_quiz_path do
    = text_field_tag :answer_name, nil, autofocus: true, required: true
    = submit_tag I18n.t('quiz.question.submit'), class: 'btn btn-primary'
  #answer_results
    %span#total_correct
      = I18n.t('quiz.question.correct')
      \: #{@current_quiz.correct}
    %span#total_incorrect
      = I18n.t('quiz.question.incorrect')
      \: #{@current_quiz.incorrect}

app/views/quizzes/result.html.haml
#quiz_result
  - if @result == :win
    %div
      = image_tag @question.profile_image_url(:correct)
    %div#main-message
      = I18n.t('quiz.result.correct')
  - else
    %div
      = image_tag @question.profile_image_url(:incorrect)
    %div#main-message
      = I18n.t('quiz.result.incorrect')
  %div= @question.user.name
  %div= @question.answer_name
  - if @question.gender == 'male'
    %div= I18n.t('common.male')
  - else
    %div= I18n.t('common.female')
  %div= "#{@question.joined_year}#{I18n.t('user_profiles.edit.year')}"
  %div= @question.group.try(:name)
  %div= @question.project.try(:name)
  %div= @question.detail
- if @current_quiz.next_question.present?
  = button_to I18n.t('quiz.result.next'), question_quiz_path , method: :get, class: 'btn btn-info margin-top', autofocus: true
  = button_to I18n.t('quiz.result.retire'), quiz_path, method: :delete, class: 'btn btn-warning margin-top'
- else
  = I18n.t('quiz.result.no_more_questions')
  = button_to I18n.t('quiz.result.finish'), quiz_path, method: :delete , class: 'btn btn-success margin-top', autofocus: true