config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }

  resource :user_profile, only: [:show, :edit, :update]
  resource :quiz, only: [:new, :create, :destroy] do
    get  :question, on: :member
    post :answer,   on: :member
    get  :result,   on: :member
  end

  root to: 'home#welcome'
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="ja")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Jagi"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand(href="#{root_path}") Jagi
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            - if user_signed_in?
              %li= link_to I18n.t('layouts.application.profile'), edit_user_profile_path
              %li= link_to I18n.t('layouts.application.quiz'), new_quiz_path
              %li= link_to I18n.t('layouts.application.help'), 'https://github.com/Yinaura/jagi/wiki/%E3%82%B8%E3%83%A3%E3%82%AE%E3%81%AE%E4%BD%BF%E3%81%84%E6%96%B9', target: '_blank'
              %li= link_to I18n.t('layouts.application.repository'), 'https://github.com/Yinaura/jagi', target: '_blank'
              %li= link_to I18n.t('layouts.application.logout'), destroy_user_session_path, method: :delete

    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield
        .col-lg-3
          .well.sidebar-nav
            %ul.nav.nav-list
              %li= link_to 'TOP', root_path
              - if user_signed_in?
                %li= link_to I18n.t('layouts.application.profile'), edit_user_profile_path
                %li= link_to I18n.t('layouts.application.quiz'), new_quiz_path
      %footer
        %p &copy; Aiming #{Time.zone.now.year}